version: "3.8"

services:
  # --- SERVICIO 1: BROKER DE MENSAJERÍA (KAFKA + ZOOKEEPER) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # CORRECCIÓN AQUÍ: Separamos los puertos (29092 interno, 9092 externo)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- SERVICIO 2: BASE DE DATOS (MYSQL) ---
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nuam_db
      MYSQL_USER: nuam_user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # --- SERVICIO 3: TU BACKEND (DJANGO + CONSUMIDOR) ---
  backend:
    build: . 
    command: python manage.py runsslserver 0.0.0.0:8000 --certificate /app/certs/cert.pem --key /app/certs/key.pem
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - db
    environment:
      # CORRECCIÓN AQUÍ: El backend ahora busca a Kafka en el puerto interno 29092
      - KAFKA_SERVER=kafka:29092
      - DB_HOST=db
      - DB_NAME=nuam_db
      - DB_USER=nuam_user
      - DB_PASSWORD=password123
      - DB_PORT=3306

volumes:
  db_data: